### ISSUE TITLE
main.py not starting

### ISSUE THREAD

**Issue by steggad** [vornao/RandomBot#9]
When I try to start main.py I receive this:

Traceback (most recent call last):
  File "/Library/Bot/RandomBot/src/main.py", line 12, in <module>
    import botcommands as commands
  File "/Library/Bot/RandomBot/src/botcommands.py", line 10, in <module>
    from telegram.inline.inputtextmessagecontent import InputTextMessageContent
ModuleNotFoundError: No module named 'telegram.inline'

Sorry, if I missed something, but I followed instructions as best as I could. I am very new to bots, so excuse me if it is a stupid question. Thanks in advance!

**Comment by vornao** [comment]
Hi @steggad! Actually, the bot uses a legacy version (13.14) of the python-telegram-bot library. I should update it to use the newer API. Meanwhile, you can try to install the legacy version with `pip install python-telegram-bot==13.14`. Please note that this api is deprecated and no longer supported.

Feel free to open a pull request if you wanna contribute to new api migration!
